synergy/urls.py
from django.conf.urls import url
from synergy.views import UsersList, CoursesList, UserDetails, UsersCoursesDetail, UsersCreate, UserDelete

urlpatterns = [
    url(r'^$', UsersList.as_view(), name="users"),
    url(r'^users/create/$', UsersCreate.as_view(), name="user_create"),

    url(r'^user/(?P<user_id>\d+)/$', UserDetails.as_view(), name="user_details"),

    url(r'^user/delete/$', UserDelete.as_view(), name="user_delete"),

    url(r'^courses/$', CoursesList.as_view(), name="courses"),

    url(r'^user_courses/$', UsersCoursesDetail.as_view(), name="user_courses")
]

synergy_way_test/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include("synergy.urls"))
]

synergy/forms.py
from django import forms


class CreateUser(forms.Form):
    custom_errors = {'required': 'This field is required', 'invalid': 'Enter a valid value'}
    email_errors = {'required': 'This field is required', 'invalid': 'Pleas enter a valid email address'}
    STATUS_CHOICES = (
        (False, 'Inactive'),
        (True, 'Active'),
    )
    name = forms.CharField(max_length=255, required=True, label='Name', error_messages=custom_errors,
                           widget=forms.TextInput(attrs={'class': 'form-control custom-usr-input'}))
    email = forms.EmailField(required=True, error_messages=email_errors,
                             widget=forms.TextInput(attrs={'class': 'form-control custom-usr-input'}))
    phone = forms.CharField(required=False, error_messages=custom_errors,
                            widget=forms.TextInput(attrs={'class': 'form-control custom-usr-input',
                                                          'type': 'tel', 'name': 'country', 'size': '4'}))
    mobile = forms.CharField(required=False, error_messages=custom_errors,
                             widget=forms.TextInput(attrs={'class': 'form-control custom-usr-input'}))
    status = forms.ChoiceField(required=False, choices=STATUS_CHOICES, error_messages=custom_errors,
                               widget=forms.Select(attrs={'class': 'form-control custom-select-cr-users'}))

    class Meta:
        fields = '__all__'


class UpdateUser(forms.Form):
    custom_errors = {'required': 'This field is required', 'invalid': 'Enter a valid value'}
    email_errors = {'required': 'This field is required', 'invalid': 'Pleas enter a valid email address'}
    STATUS_CHOICES = (
        (False, 'Inactive'),
        (True, 'Active'),
    )
    name = forms.CharField(max_length=255, required=True, label='Name', error_messages=custom_errors,
                           widget=forms.TextInput(attrs={'class': 'form-control custom-usr-input',
                                                         'readonly': 'readonly'}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control custom-usr-input'}),
                             error_messages=email_errors)
    phone = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control custom-usr-input',
                                                                          'type': 'tel', 'name': 'country',
                                                                          'size': '4'}), error_messages=custom_errors)
    mobile = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control custom-usr-input'}),
                             error_messages=custom_errors)
    status = forms.ChoiceField(required=False, choices=STATUS_CHOICES, error_messages=custom_errors,
                               widget=forms.Select(attrs={'class': 'form-control custom-select-cr-users'}))

    class Meta:
        fields = '__all__'

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
        <meta charset="UTF-8">

        <title>Synergy Way task</title>

        <script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/9.0.2/js/utils.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/9.0.2/js/intlTelInput.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>

        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
        <link rel="stylesheet" type="text/css"
              href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/8.1.0/css/intlTelInput.css"/>
        <link rel="stylesheet" type="text/css"
              href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/9.0.2/img/flags.png"/>
        <link rel="stylesheet" type="text/css"
              href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/9.0.2/img/flags@2x.png"/>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
        <link href="https://fonts.googleapis.com/css?family=Devonshire|Pacifico" rel="stylesheet">
        <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    {% endblock %}
</head>

<div class="row nav-bar-row">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
        <p class="test-for-you">Test for You</p>
    </div>
    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
        <a href="{% url 'users' %}" class="nav-users"><p>Users</p></a>
    </div>
    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
        <a href="{% url 'courses' %}" class="nav-courses"><p>Courses</p></a>
    </div>
</div>


<body>
{% block body %}
{% endblock %}
</body>

</html>

templates/courses_list.html
{% extends 'base.html' %}

{% block body %}
    <div class="row first-space" style="padding-top: 5.5em;">
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5"></div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
            <h1>COURSES</h1>
        </div>
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5"></div>
    </div>
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-7 head-section1">
            <h4 class="col-title1">NAME</h4>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-3 head-section2">
            <h4 class="col-title2">CODE</h4>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
    </div>
    {% for course in data %}
        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-7 field-col1" id="courseName">
                <h4 class="field-col1-text">
                    {{ course.name }}
                </h4>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 field-col2" id="courseCode">
                <h4 class="field-col2-text">{{ course.code }}</h4>
            </div>
        </div>
    {% endfor %}

{% endblock %}

templates/user_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}
    <div class="row firs-space">
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
            <a href="{% url 'users' %}">
                <div class="back-button">
                    <div class="back-button-hrz"></div>
                    <div class="back-button-vrt"></div>
                </div>
            </a>
        </div>
        <div class="col-lg-5 col-md-4 col-sm-4 col-xs-4">
            <h3 class="custom-title-cr-user">CREATE USER</h3>
        </div>
        {% if successful %}
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                <p class="successful-message" id="msg">User created successfully</p>
            </div>
        {% endif %}
    </div>
    <form action="" method="post" id="contactForm">
        {% csrf_token %}
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <div class="input-custom-form">
                    <h4 class="asterisk">*</h4>
                    <h4>Name</h4>
                </div>
                {{ user_form.name }}
            </div>
            {% if user_form.errors.name %}
                <p class="error-icon">!</p>
                {{ user_form.errors.name }}
            {% endif %}
        </div>
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <div class="input-custom-form">
                    <h4 class="asterisk">*</h4>
                    <h4>E-mail</h4>
                </div>
                {{ user_form.email }}
            </div>
            {% if user_form.errors.email %}
                <p class="error-icon">!</p>
                {{ user_form.errors.email }}
            {% endif %}
        </div>
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <div class="input-cutom-form">
                    <h4 class="no-asterisk">Phone</h4>
                </div>
                {{ user_form.phone }}
            </div>
            {% if user_form.errors.phone %}
                <p class="error-icon">!</p>
                {{ user_form.errors.phone }}
            {% endif %}
        </div>
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <div class="input-cutom-form">
                    <h4 class="no-asterisk">Mobile phone</h4>
                </div>
                {{ user_form.mobile }}
                {% if user_form.errors.mobile %}
                    <p class="error-icon">!</p>
                    {{ user_form.errors.mobile }}
                {% endif %}
            </div>
        </div>
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <div class="input-cutom-form">
                    <h4 class="no-asterisk">Status</h4>
                    {{ user_form.status }}
                    <button type="submit" class="btn btn-success btn-custom-create">Create</button>
                </div>
            </div>
        </div><!--6 row: <title Status>, <select Status>-->
    </form>
    <script>
        function removeMsg() {
            $('#msg').css("display", "none");
        }
        function gotoUsers() {
            window.location.assign("{% url 'users' %}");
        }
        $(document).ready(function () {
            if ($('#msg').length) {
                setTimeout(removeMsg, 3000);
                setTimeout(gotoUsers, 4000);
            }
            $("#id_phone").intlTelInput({
                allowExtensions: true,
                defaultCountry: "auto",
                preventInvalidNumbers: true,
                utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/9.0.2/js/utils.js"
            });
            $("#id_mobile").intlTelInput({
                numberType: "MOBILE",
                preventInvalidNumbers: true,
                utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/9.0.2/js/utils.js"
            });
        });
    </script>
    <style>
        .intl-tel-input {
            width: 100% !important;
            margin-left: 1em !important;
        }
    </style>
{% endblock %}

templates/user_detail.html
{% extends 'base.html' %}

{% block body %}
    <div class="row firs-space">
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
            <a href="{% url 'users' %}">
                <div class="back-background">
                    <div class="back-horizontal-line"></div>
                    <div class="back-vertical-line"></div>
                </div>
            </a>
        </div>
        <div class="col-lg-3 col-md-2 col-sm-2 col-xs-2">
            <h3 class="user-title">CHANGE USER</h3>
        </div>

        <div class="col-lg-1"></div>

        {% if successful %}
            <div class="col-lg-3 col-md-5 col-sm-5 col-xs-5">
                <div class="info-button" id="msg">
                    <h5 class="info-button-text">{{ successful }}</h5>
                </div>
            </div>
        {% endif %}
    </div>
    <form action="" method="post" id="contactForm">
        {% csrf_token %}
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <div class="input-custom-form">
                    <h4 class="custom-title">Name</h4>
                </div>
                {{ user_form.name }}
            </div>
            {% if user_form.errors.name %}
                <p class="error-icon">!</p>
                {{ user_form.errors.name }}
            {% endif %}
        </div>
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <div class="input-custom-form">
                    <h4 class="asterisk">*</h4>
                    <h4>E-mail</h4>
                </div>
                {{ user_form.email }}
            </div>
            {% if user_form.errors.email %}
                <p class="error-icon">!</p>
                {{ user_form.errors.email }}
            {% endif %}
        </div>
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <div class="input-custom-form">
                    <h4 class="no-asterisk">Phone</h4>
                </div>
                {{ user_form.phone }}
            </div>
            {% if user_form.errors.phone %}
                <p class="error-icon">!</p>
                {{ user_form.errors.phone }}
            {% endif %}
        </div>
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <div class="input-custom-form">
                    <h4 class="no-asterisk">Mobile phone</h4>
                </div>
                {{ user_form.mobile }}
            </div>
            {% if user_form.errors.mobile %}
                <p class="error-icon">!</p>
                {{ user_form.errors.mobile }}
            {% endif %}
        </div>
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <div class="input-custom-form">
                    <h4 class="no-asterisk">Status</h4>
                    {{ user_form.status }}
                </div>
            </div>
        </div>
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                <div class="input-custom-form">
                    <h4 class="no-asterisk">Courses</h4>
                    {{ user_form.courses }}
                    {% if courses %}
                        <select class="form-control courses" id="course">
                            {% for course in courses %}
                                {% if course.id not in user_courses %}
                                    <option value="{{ course.id }}">{{ course.name }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1" style="padding-top: 3.3em;">
                <a href="javascript:void(0);" onclick="add_course()" class="add-button-a">
                    <div class="add-button-background">
                        <div class="add-button-horizontal-line"></div>
                        <div class="add-button-vertical-line"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3" id="courses_added" style="padding-right: 0;">
                {% for course in courses %}
                    {% if course.id in user_courses %}
                        <p class="added-courses">{{ course.name }}
                            <a href="javascript:void(0);" onclick="remove_course()">
                                <span value="{{ course.id }}" class="glyphicon glyphicon-remove"></span>
                            </a>
                        </p>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5"></div>
        </div>
        <div class="row n-space">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <button type="submit" class="btn-save btn btn-success">Save</button>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5"></div>
        </div>
    </form>
    <script>
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                    // Only send the token to relative URLs i.e. locally.
                    xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                }
            }
        });

        function add_course() {
            var selected_course = $('#course :selected');
            var course_id = JSON.parse($('#course').val());
            var course_name = selected_course.text();

            $.ajax({
                url: {% url "user_courses" %},
                type: "POST",
                data: {
                    user_id: {{ user_id }},
                    course_id: course_id,
                    available: false
                },
                success: function (data) {
                    $('#courses_added').prepend($(
                            "<p class='added-courses'>" + course_name + "<a href='javascript:void(0);' onclick='remove_course()'>"
                            + "<span value='" + course_id + "' class='glyphicon glyphicon-remove'></span></a></p>"));
                    selected_course.remove();

                    if ($('#course').has('option').length == 0) {
                        $('#course').css('display', 'none');
                        $('.add-button-a').css('display', 'none');
                    }
                }
            });
        }

        function remove_course() {
            var target = event.target;
            var target_parent = $(target).parent().parent();

            var course_id = JSON.parse(target.getAttribute('value'));
            var course_name = $.trim(target_parent.text());

            $.ajax({
                url: {% url "user_courses" %},
                type: "POST",
                data: {
                    user_id: {{ user_id }},
                    course_id: course_id,
                    available: true
                },
                success: function (data) {
                    if ($('#course').css('display') == 'none') {
                        $('#course').css('display', 'inline');
                        $('.add-button-a').css('display', 'inline');
                    }

                    $('#course').append($('<option/>', {value: course_id, text: course_name}));
                    target_parent.css('display', 'none');
                }
            });

        }

        function remove_msg() {
            $('#msg').css("display", "none");
        }

        function redirect_users() {
            window.location.assign("{% url 'users' %}");
        }

        $(document).ready(function () {
            if ($('#course').has('option').length == 0) {
                $('#course').css('display', 'none');
                $('.add-button-a').css('display', 'none');
            }

            if ($('#msg').length) {
                setTimeout(remove_msg, 3000);
                setTimeout(redirect_users, 4000);
            }
            $("#id_phone").intlTelInput({
                allowExtensions: true,
                defaultCountry: "auto",
                preventInvalidNumbers: true,
                utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/9.0.2/js/utils.js"
            });
            $("#id_mobile").intlTelInput({
                numberType: "MOBILE",
                preventInvalidNumbers: true,
                utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/9.0.2/js/utils.js"
            });
        });
    </script>
    <style>
        .intl-tel-input {
            width: 100% !important;
            margin-left: 1em !important;
        }
    </style>
{% endblock %}

templates/users_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}
    <div class="row firs-space">
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
        <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1" style="width: 5em;">
            <a href="{% url 'user_create' %}">

                <div class="icon-plus-bgr">
                    <div class="icon-plus-hrz"></div>
                    <div class="icon-plus-vrt"></div>
                </div>

            </a>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
            <div class="input-group ">
                <form action="{% url 'users' %}" method="GET" style="display: inline-flex;">
                    <button type="submit" class="input-group-addon">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                    <input onkeydown="if (event.keyCode == 13) { this.form.submit(); return false; }"
                           type="text"
                           name="username"
                           class="form-control custom-input"
                           id="search">
                </form>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-2 col-xs-2">
            <h2 style="margin-top: 0.2em;">USERS</h2>
        </div>
        <div class="col-lg-1 col-md-1 col-sm-2 col-xs-2">
            <select class="form-control custom-select" id="num_fields">
                <option value="15">15</option>
                <option value="25">25</option>
                <option value="40">40</option>
            </select>
        </div>
    </div>

    <div class="row table-head-pad" style="padding-top: 3em;">
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 table-head-color">
            <h4 style="color: white;">NAME</h4>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 table-head-color">
            <h4 style="color: white;">E-MAIL</h4>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 table-head-color">
            <h4 style="color: white;">STATUS</h4>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 table-head-color" style="max-width: 15.3em;">
            <h4 style="color: white;float: right;padding-right: 2em;">ACTION</h4>
        </div>
    </div>
    {% for field in data %}
        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 custom-field">
                <h5>{{ field.name }}</h5>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 custom-field">
                <h5>{{ field.email }}</h5>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 custom-field">
                {% if field.status %}
                    <h5>Active</h5>
                {% else %}
                    <h5 style="color: red;">Inactive</h5>
                {% endif %}
            </div>
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 custom-field-action">
                <a href="javascript:void(0);" onclick="del({{ field.id }})">
                    <div class="delete-icon-dg">
                        <i class="fa fa-trash-o"></i>
                    </div>
                </a>
                <a href="{% url 'user_details' user_id=field.id %}">
                    <div class="change-icon-dg">
                        <i class="fa fa-pencil"></i>
                    </div>
                </a>
            </div>
        </div>
    {% endfor %}

    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <div class="container" style="margin-left: 15%;">
                <ul class="pagination" id="pagination">
                    <li><a href="javascript:void(0);" onclick="back()">«</a></li>
                    <li><a href="javascript:void(0);" onclick="go_to_url(1)">1</a></li>
                    <li><a href="javascript:void(0);" onclick="go_to_url(2)">2</a></li>
                    <li><a href="javascript:void(0);" onclick="go_to_url(3)">3</a></li>
                    <li><a href="javascript:void(0);" onclick="go_to_url(4)">4</a></li>
                    <li><a href="javascript:void(0);" onclick="go_to_url(5)">5</a></li>
                    <li><a href="javascript:void(0);" onclick="forward()">»</a></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
    </div>

    <script>
        window.onload = function (e) {
            var pages = $(".pagination").find("li");
            var page = (parseInt(localStorage['page']) + 1);
            if ($_GET('page') == undefined) {
                $(pages[1]).attr("class", "active");
            } else {
                $(pages[page]).attr("class", "active");
            }
            $("#num_fields").val(localStorage['num']);
        };

        if (localStorage['num'] == undefined) {
            localStorage['num'] = 15;
        }

        function currentPage() {
            var pages = $(".pagination").find("li");
            for (var i = 0, j = pages.length; i < j; i++) {
                if ($(pages[i]).hasClass("active")) {
                    return pages[i].children[0].text[0];
                }
            }
        }

        function go_to_url(page) {
            var num = localStorage['num'];
            var page_num = Math.abs(parseInt(page) - 1);
            var url = "http://" + location.host + "/?per_page=" + num + "&page=" + page_num;
            if (parseInt(page_num) >= 0) {
                localStorage['page'] = page_num;
                window.location.assign(url);
                return url;
            }
        }

        $("#num_fields").click(function () {
            var current_page = currentPage();
            localStorage['num'] = this.value;
            go_to_url(current_page)
        });

        function back() {
            var current_page = currentPage();
            if (current_page > 1) {
                go_to_url(Math.abs((parseInt(current_page) - 1)));
            } else {
                go_to_url(parseInt(current_page));
            }
        }
        function forward() {
            var current_page = currentPage();
            go_to_url((parseInt(current_page) + 1));
        }

        function del(pk) {
            $.ajax({
                url: "{% url 'user_delete' %}",
                type: "POST",
                data: {"user_id": pk, "csrfmiddlewaretoken": "{{csrf_token}}"},
                success: 'success'
            });
            $(event.target).parent().parent().parent().parent().css('display', 'none');
        }
    </script>

{% endblock %}